<a href="https://colab.research.google.com/github/satwikbarik2-hub/Data-preprocessing/blob/main/pan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data=[1,2,3,4,5]
series=pd.Series(data)
print("series\n",series)

series
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [ ]:
data=[1,2,3]
index=['a','b','c']
pd.Series(data,index=index)

a    1
b    2
c    3
dtype: int64

In [ ]:
#dataframe
#create dataframe from dictionary of list
import pandas as pd
data={
    'name':['satwik','hari','soumesh'],
    'age':[25,30,45],
    'city':["jsg","banglore",'mumbai']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

      name  age      city
0   satwik   25       jsg
1     hari   30  banglore
2  soumesh   45    mumbai
<class 'pandas.core.frame.DataFrame'>

In [ ]:
#create dataframe from list of dictionaries
data=[
    {'name':'satwik','age':20,'city':'jsg'},
    {'name':'hari','age':21,'city':'jsg'},
    {'name':'wik','age':22,'city':'jsg'},
    {'name':'sa','age':24,'city':'jsg'}
]
df=pd.DataFrame(data)
print(df)
print(type(df))

     name  age city
0  satwik   20  jsg
1    hari   21  jsg
2     wik   22  jsg
3      sa   24  jsg
<class 'pandas.core.frame.DataFrame'>

In [ ]:
df

     name  age city
0  satwik   20  jsg
1    hari   21  jsg
2     wik   22  jsg
3      sa   24  jsg

In [ ]:
df['name']

0    satwik
1      hari
2       wik
3        sa
Name: name, dtype: object

In [ ]:
df.loc[0]

name    satwik
age         20
city       jsg
Name: 0, dtype: object

In [ ]:
df.iloc[0][2]

/tmp/ipykernel_893/2519637664.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2]

'jsg'

In [ ]:
#accessing specified element
df.at[2,'age']

np.int64(22)

In [ ]:
df.iat[2,2]

'jsg'

In [ ]:
df

     name  age city
0  satwik   20  jsg
1    hari   21  jsg
2     wik   22  jsg
3      sa   24  jsg

In [ ]:
df['salary']=500000,60000,70000,80000
df

     name  age city  salary
0  satwik   20  jsg  500000
1    hari   21  jsg   60000
2     wik   22  jsg   70000
3      sa   24  jsg   80000

In [ ]:
df.drop(0,inplace=True)

KeyError: '[0] not found in axis'

In [ ]:
df

   name  age city  salary
1  hari   21  jsg   60000
2   wik   22  jsg   70000
3    sa   24  jsg   80000